In [23]:
#Import Dependencies
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.types import String

In [24]:
#Loading CSV files
data = "Resources1/listings 2.csv"

In [25]:
#CSV to DataFrame
data_df = pd.read_csv(data, low_memory=False)
data_df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,958,https://www.airbnb.com/rooms/958,20200313233841,2020-03-14,"Bright, Modern Garden Unit - 1BR/1B",New update: the house next door is under const...,"Newly remodeled, modern, and bright garden uni...",New update: the house next door is under const...,none,*Quiet cul de sac in friendly neighborhood *St...,...,t,f,moderate,f,f,1,1,0,0,1.83
1,5858,https://www.airbnb.com/rooms/5858,20200313233841,2020-03-14,Creative Sanctuary,NaN,We live in a large Victorian house on a quiet ...,We live in a large Victorian house on a quiet ...,none,I love how our neighborhood feels quiet but is...,...,f,f,strict_14_with_grace_period,f,f,1,1,0,0,0.84
2,7918,https://www.airbnb.com/rooms/7918,20200313233841,2020-03-14,A Friendly Room - UCSF/USF - San Francisco,Nice and good public transportation. 7 minute...,"Settle down, S.F. resident, student, hospital,...",Nice and good public transportation. 7 minute...,none,"Shopping old town, restaurants, McDonald, Whol...",...,f,f,strict_14_with_grace_period,f,f,9,0,9,0,0.14
3,8142,https://www.airbnb.com/rooms/8142,20200313233841,2020-03-14,Friendly Room Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,"Settle down, S.F. resident, student, hospital,...",Nice and good public transportation. 7 minute...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,9,0,9,0,0.12
4,8339,https://www.airbnb.com/rooms/8339,20200313233841,2020-03-14,Historic Alamo Square Victorian,Pls email before booking. Interior featured i...,Please send us a quick message before booking ...,Pls email before booking. Interior featured i...,none,NaN,...,f,f,moderate,t,t,2,2,0,0,0.22

In [26]:
#getting columns' names for data set selection
data_df.columns.tolist()

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'name',
 'summary',
 'space',
 'description',
 'experiences_offered',
 'neighborhood_overview',
 'notes',
 'transit',
 'access',
 'interaction',
 'house_rules',
 'thumbnail_url',
 'medium_url',
 'picture_url',
 'xl_picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'street',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'city',
 'state',
 'zipcode',
 'market',
 'smart_location',
 'country_code',
 'country',
 'latitude',
 'longitude',
 'is_location_exact',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bedrooms',
 'beds',
 'bed_type',
 'amenities',
 'square_feet',
 'price',
 'weekly_price',
 'monthly_price',
 'security_deposit',
 'cleaning_fee',
 'guests_included',
 'extra_people',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'requires_license',
 'license',
 'jurisdiction_names',
 'instant_bookable',
 'is_business_travel_ready',
 'cancellation_policy',
 'require_guest_profile_picture',
 'require_guest_phone_verification',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

In [27]:
#Selecting colums for a new data frame
mapping_select = ["id", "name", "neighbourhood_cleansed","latitude","longitude","room_type","minimum_maximum_nights","license"]
#Making a copy of the new data set
mapping_data= data_df[mapping_select].copy()
mapping_data

,id,name,neighbourhood_cleansed,latitude,longitude,room_type,minimum_maximum_nights,license
0,958,"Bright, Modern Garden Unit - 1BR/1B",Western Addition,37.769310,-122.433860,Entire home/apt,30,STR-0001256
1,5858,Creative Sanctuary,Bernal Heights,37.745110,-122.421020,Entire home/apt,60,NaN
2,7918,A Friendly Room - UCSF/USF - San Francisco,Haight Ashbury,37.765550,-122.452130,Private room,60,NaN
3,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,Haight Ashbury,37.765550,-122.452130,Private room,90,NaN
4,8339,Historic Alamo Square Victorian,Western Addition,37.775250,-122.436370,Entire home/apt,111,STR-0000264
...,...,...,...,...,...,...,...,...
8567,42888879,Spacious Queen Room in NOPA,Haight Ashbury,37.775225,-122.447786,Private room,365,NaN
8568,42891188,One Bedroom Apartment near Rincon Center,Financial District,37.792271,-122.391566,Entire home/apt,1125,NaN
8569,42893191,908. Co-living | Private room,Russian Hill,37.797580,-122.413360,Private room,1125,NaN
8570,42893565,908. Co-living | Private room,Nob Hill,37.796669,-122.412140,Private room,1125,NaN
8571,42893935,908. Co-living | Private room with a bathroom,Russian Hill,37.797580,-122.413360,Private room,1125,NaN

In [28]:
#Checking data types of each column
mapping_data.dtypes

id                          int64
name                       object
neighbourhood_cleansed     object
latitude                  float64
longitude                 float64
room_type                  object
minimum_maximum_nights      int64
license                    object
dtype: object

In [29]:
#Pulling and counting unique values in room_type column
mapping_data.room_type.value_counts()

Entire home/apt    5065
Private room       3094
Shared room         313
Hotel room          100
Name: room_type, dtype: int64

In [30]:
#Dropping dublicates in ID column
mapping_data.drop_duplicates("id", inplace=True)
#Dropping rows with "Hotel room" value in room_type, because we want to analyze privetly owned properties managed by a host
mapping_df = mapping_data[mapping_data.room_type != 'Hotel room']
mapping_df

,id,name,neighbourhood_cleansed,latitude,longitude,room_type,minimum_maximum_nights,license
0,958,"Bright, Modern Garden Unit - 1BR/1B",Western Addition,37.769310,-122.433860,Entire home/apt,30,STR-0001256
1,5858,Creative Sanctuary,Bernal Heights,37.745110,-122.421020,Entire home/apt,60,NaN
2,7918,A Friendly Room - UCSF/USF - San Francisco,Haight Ashbury,37.765550,-122.452130,Private room,60,NaN
3,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,Haight Ashbury,37.765550,-122.452130,Private room,90,NaN
4,8339,Historic Alamo Square Victorian,Western Addition,37.775250,-122.436370,Entire home/apt,111,STR-0000264
...,...,...,...,...,...,...,...,...
8567,42888879,Spacious Queen Room in NOPA,Haight Ashbury,37.775225,-122.447786,Private room,365,NaN
8568,42891188,One Bedroom Apartment near Rincon Center,Financial District,37.792271,-122.391566,Entire home/apt,1125,NaN
8569,42893191,908. Co-living | Private room,Russian Hill,37.797580,-122.413360,Private room,1125,NaN
8570,42893565,908. Co-living | Private room,Nob Hill,37.796669,-122.412140,Private room,1125,NaN
8571,42893935,908. Co-living | Private room with a bathroom,Russian Hill,37.797580,-122.413360,Private room,1125,NaN

In [31]:
#Dropping rows with "License not needed per OSTR" value in license
mapping_df_2 = mapping_df[mapping_df.license != 'License not needed per OSTR']
mapping_df_2

,id,name,neighbourhood_cleansed,latitude,longitude,room_type,minimum_maximum_nights,license
0,958,"Bright, Modern Garden Unit - 1BR/1B",Western Addition,37.769310,-122.433860,Entire home/apt,30,STR-0001256
1,5858,Creative Sanctuary,Bernal Heights,37.745110,-122.421020,Entire home/apt,60,NaN
2,7918,A Friendly Room - UCSF/USF - San Francisco,Haight Ashbury,37.765550,-122.452130,Private room,60,NaN
3,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,Haight Ashbury,37.765550,-122.452130,Private room,90,NaN
4,8339,Historic Alamo Square Victorian,Western Addition,37.775250,-122.436370,Entire home/apt,111,STR-0000264
...,...,...,...,...,...,...,...,...
8567,42888879,Spacious Queen Room in NOPA,Haight Ashbury,37.775225,-122.447786,Private room,365,NaN
8568,42891188,One Bedroom Apartment near Rincon Center,Financial District,37.792271,-122.391566,Entire home/apt,1125,NaN
8569,42893191,908. Co-living | Private room,Russian Hill,37.797580,-122.413360,Private room,1125,NaN
8570,42893565,908. Co-living | Private room,Nob Hill,37.796669,-122.412140,Private room,1125,NaN
8571,42893935,908. Co-living | Private room with a bathroom,Russian Hill,37.797580,-122.413360,Private room,1125,NaN

In [32]:
#Dropping rows with "Licensed Hotel/B&B" value in license
mapping_df_2 = mapping_df_2[mapping_df_2.license != 'Licensed Hotel/B&B']
mapping_df_2

,id,name,neighbourhood_cleansed,latitude,longitude,room_type,minimum_maximum_nights,license
0,958,"Bright, Modern Garden Unit - 1BR/1B",Western Addition,37.769310,-122.433860,Entire home/apt,30,STR-0001256
1,5858,Creative Sanctuary,Bernal Heights,37.745110,-122.421020,Entire home/apt,60,NaN
2,7918,A Friendly Room - UCSF/USF - San Francisco,Haight Ashbury,37.765550,-122.452130,Private room,60,NaN
3,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,Haight Ashbury,37.765550,-122.452130,Private room,90,NaN
4,8339,Historic Alamo Square Victorian,Western Addition,37.775250,-122.436370,Entire home/apt,111,STR-0000264
...,...,...,...,...,...,...,...,...
8567,42888879,Spacious Queen Room in NOPA,Haight Ashbury,37.775225,-122.447786,Private room,365,NaN
8568,42891188,One Bedroom Apartment near Rincon Center,Financial District,37.792271,-122.391566,Entire home/apt,1125,NaN
8569,42893191,908. Co-living | Private room,Russian Hill,37.797580,-122.413360,Private room,1125,NaN
8570,42893565,908. Co-living | Private room,Nob Hill,37.796669,-122.412140,Private room,1125,NaN
8571,42893935,908. Co-living | Private room with a bathroom,Russian Hill,37.797580,-122.413360,Private room,1125,NaN

In [33]:
#Converting all lowercase characters in "license" column into uppercase characters for checking values to 
#determine legal/illigal status
mapping_df_2['license'].str.upper()
mapping_df_2

,id,name,neighbourhood_cleansed,latitude,longitude,room_type,minimum_maximum_nights,license
0,958,"Bright, Modern Garden Unit - 1BR/1B",Western Addition,37.769310,-122.433860,Entire home/apt,30,STR-0001256
1,5858,Creative Sanctuary,Bernal Heights,37.745110,-122.421020,Entire home/apt,60,NaN
2,7918,A Friendly Room - UCSF/USF - San Francisco,Haight Ashbury,37.765550,-122.452130,Private room,60,NaN
3,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,Haight Ashbury,37.765550,-122.452130,Private room,90,NaN
4,8339,Historic Alamo Square Victorian,Western Addition,37.775250,-122.436370,Entire home/apt,111,STR-0000264
...,...,...,...,...,...,...,...,...
8567,42888879,Spacious Queen Room in NOPA,Haight Ashbury,37.775225,-122.447786,Private room,365,NaN
8568,42891188,One Bedroom Apartment near Rincon Center,Financial District,37.792271,-122.391566,Entire home/apt,1125,NaN
8569,42893191,908. Co-living | Private room,Russian Hill,37.797580,-122.413360,Private room,1125,NaN
8570,42893565,908. Co-living | Private room,Nob Hill,37.796669,-122.412140,Private room,1125,NaN
8571,42893935,908. Co-living | Private room with a bathroom,Russian Hill,37.797580,-122.413360,Private room,1125,NaN

In [34]:
#Filtering data set by  "Entire home/apt" value in "room_type" column
mapping_new = mapping_df_2.loc[mapping_df_2['room_type'] == "Entire home/apt"]
mapping_new

,id,name,neighbourhood_cleansed,latitude,longitude,room_type,minimum_maximum_nights,license
0,958,"Bright, Modern Garden Unit - 1BR/1B",Western Addition,37.769310,-122.433860,Entire home/apt,30,STR-0001256
1,5858,Creative Sanctuary,Bernal Heights,37.745110,-122.421020,Entire home/apt,60,NaN
4,8339,Historic Alamo Square Victorian,Western Addition,37.775250,-122.436370,Entire home/apt,111,STR-0000264
7,10251,Victorian Suite in Inner Mission,Mission,37.758310,-122.413860,Entire home/apt,60,STR-0001558
8,10578,Classic Nob Hill Studio - Roof Deck,Nob Hill,37.791430,-122.415440,Entire home/apt,180,NaN
...,...,...,...,...,...,...,...,...
8560,42877943,Comfort in the heart of San Francisco!,Financial District,37.790960,-122.392890,Entire home/apt,1125,NaN
8561,42878952,One Bedroom in the Heart of SF!,Financial District,37.791210,-122.391270,Entire home/apt,1125,NaN
8562,42880113,"Crisp SoMa 2BR w/ Gym, Courtyard, walk to Uber...",South of Market,37.777760,-122.415980,Entire home/apt,1125,NaN
8563,42881117,Newly Remodeled Mission Flat,Mission,37.750808,-122.407721,Entire home/apt,1125,NaN
8568,42891188,One Bedroom Apartment near Rincon Center,Financial District,37.792271,-122.391566,Entire home/apt,1125,NaN

In [35]:
#Adding "illigal" column to fill in after checking "for-loop" condotions in each row of the data
mapping_new['illegal'] = ''
mapping_new

C:\Users\melis\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,id,name,neighbourhood_cleansed,latitude,longitude,room_type,minimum_maximum_nights,license,illegal
0,958,"Bright, Modern Garden Unit - 1BR/1B",Western Addition,37.769310,-122.433860,Entire home/apt,30,STR-0001256,
1,5858,Creative Sanctuary,Bernal Heights,37.745110,-122.421020,Entire home/apt,60,NaN,
4,8339,Historic Alamo Square Victorian,Western Addition,37.775250,-122.436370,Entire home/apt,111,STR-0000264,
7,10251,Victorian Suite in Inner Mission,Mission,37.758310,-122.413860,Entire home/apt,60,STR-0001558,
8,10578,Classic Nob Hill Studio - Roof Deck,Nob Hill,37.791430,-122.415440,Entire home/apt,180,NaN,
...,...,...,...,...,...,...,...,...,...
8560,42877943,Comfort in the heart of San Francisco!,Financial District,37.790960,-122.392890,Entire home/apt,1125,NaN,
8561,42878952,One Bedroom in the Heart of SF!,Financial District,37.791210,-122.391270,Entire home/apt,1125,NaN,
8562,42880113,"Crisp SoMa 2BR w/ Gym, Courtyard, walk to Uber...",South of Market,37.777760,-122.415980,Entire home/apt,1125,NaN,
8563,42881117,Newly Remodeled Mission Flat,Mission,37.750808,-122.407721,Entire home/apt,1125,NaN,
8568,42891188,One Bedroom Apartment near Rincon Center,Financial District,37.792271,-122.391566,Entire home/apt,1125,NaN,

In [36]:
#For-loop conditions which determine legal/illigal status of listed properties in San Francisco county
for i in range(len(mapping_new)) : 
    licence =  mapping_new.iloc[i,7] #assigning licence string into a variable
    #print(licence)
    #print(mapping_new.iloc[i,6])
    if isinstance(licence, float) == False:
        if (mapping_new.iloc[i,6] <= 90 and licence.startswith('STR')) :
            mapping_new.iloc[i,8]= 'legal'
            #add 'legal' to the illegal column if min-max rental nights equal or less then 90 night and property has license # starting with "STR"
        else:
            mapping_new.iloc[i,8]= 'illegal'
            #add 'illegal' to the legal column if min-max rental nights more then 90 or property has no license # starting with "STR"
    else: 
        mapping_new.iloc[i,8]= 'illegal'

C:\Users\melis\Anaconda3\lib\site-packages\pandas\core\indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [37]:
#checking Data Frame
mapping_new

,id,name,neighbourhood_cleansed,latitude,longitude,room_type,minimum_maximum_nights,license,illegal
0,958,"Bright, Modern Garden Unit - 1BR/1B",Western Addition,37.769310,-122.433860,Entire home/apt,30,STR-0001256,legal
1,5858,Creative Sanctuary,Bernal Heights,37.745110,-122.421020,Entire home/apt,60,NaN,illegal
4,8339,Historic Alamo Square Victorian,Western Addition,37.775250,-122.436370,Entire home/apt,111,STR-0000264,illegal
7,10251,Victorian Suite in Inner Mission,Mission,37.758310,-122.413860,Entire home/apt,60,STR-0001558,legal
8,10578,Classic Nob Hill Studio - Roof Deck,Nob Hill,37.791430,-122.415440,Entire home/apt,180,NaN,illegal
...,...,...,...,...,...,...,...,...,...
8560,42877943,Comfort in the heart of San Francisco!,Financial District,37.790960,-122.392890,Entire home/apt,1125,NaN,illegal
8561,42878952,One Bedroom in the Heart of SF!,Financial District,37.791210,-122.391270,Entire home/apt,1125,NaN,illegal
8562,42880113,"Crisp SoMa 2BR w/ Gym, Courtyard, walk to Uber...",South of Market,37.777760,-122.415980,Entire home/apt,1125,NaN,illegal
8563,42881117,Newly Remodeled Mission Flat,Mission,37.750808,-122.407721,Entire home/apt,1125,NaN,illegal
8568,42891188,One Bedroom Apartment near Rincon Center,Financial District,37.792271,-122.391566,Entire home/apt,1125,NaN,illegal

In [38]:
#Creating output csv file 
mapping_new.to_csv("Output/mapping_data.csv", index = False)

In [39]:
#Saving priviously created data frame to new variable 
roomtype_df = mapping_df_2
roomtype_df

,id,name,neighbourhood_cleansed,latitude,longitude,room_type,minimum_maximum_nights,license
0,958,"Bright, Modern Garden Unit - 1BR/1B",Western Addition,37.769310,-122.433860,Entire home/apt,30,STR-0001256
1,5858,Creative Sanctuary,Bernal Heights,37.745110,-122.421020,Entire home/apt,60,NaN
2,7918,A Friendly Room - UCSF/USF - San Francisco,Haight Ashbury,37.765550,-122.452130,Private room,60,NaN
3,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,Haight Ashbury,37.765550,-122.452130,Private room,90,NaN
4,8339,Historic Alamo Square Victorian,Western Addition,37.775250,-122.436370,Entire home/apt,111,STR-0000264
...,...,...,...,...,...,...,...,...
8567,42888879,Spacious Queen Room in NOPA,Haight Ashbury,37.775225,-122.447786,Private room,365,NaN
8568,42891188,One Bedroom Apartment near Rincon Center,Financial District,37.792271,-122.391566,Entire home/apt,1125,NaN
8569,42893191,908. Co-living | Private room,Russian Hill,37.797580,-122.413360,Private room,1125,NaN
8570,42893565,908. Co-living | Private room,Nob Hill,37.796669,-122.412140,Private room,1125,NaN
8571,42893935,908. Co-living | Private room with a bathroom,Russian Hill,37.797580,-122.413360,Private room,1125,NaN

In [40]:
#Making a copy of a data set
room_type_df= mapping_df_2.copy()
#Grouping data by "room_type" and counting values
roomtype_new = room_type_df.groupby('room_type')['id'].count()
roomtype_new

room_type
Entire home/apt    4822
Private room       2770
Shared room         284
Name: id, dtype: int64

In [41]:
#Creating new data frame using groupby results
room_type_df = pd.DataFrame(roomtype_new)
#Renaming column "id" to "count"
room_type_df = room_type_df.rename(columns={ "id": "count"})
#room_type_df = room_type_df.reset_index()
room_type_df

                 count
room_type
Entire home/apt   4822
Private room      2770
Shared room        284

In [42]:
#Calculating sum of all room types to use for percentage calculation
total_count = sum(room_type_df["count"])
#Creating variable to hold percentage data and calculating percentage 
prcnt = (room_type_df["count"])/total_count*100

In [43]:
#Adding "percentage" column to Data Ftame in % format
room_type_df['percentage'] = prcnt.map('{:,.2f}%'.format)
room_type_df

                 count percentage
room_type
Entire home/apt   4822     61.22%
Private room      2770     35.17%
Shared room        284      3.61%

In [44]:
room_type_df.to_csv("Output/grouped_roomtype.csv")

In [45]:
#Making a copy of a data set
legal_df= mapping_new.copy()
#Grouping data by legal/illigal status and counting values
legal_df = legal_df.groupby('illegal')['id'].count()
legal_df

illegal
illegal    3850
legal       972
Name: id, dtype: int64

In [46]:
#Creating new data frame using groupby results
leg_illeg_df = pd.DataFrame(legal_df)
#Renaming column "id" to "count"
leg_illeg_df = leg_illeg_df.rename(columns={ "id": "count"})
leg_illeg_df

         count
illegal
illegal   3850
legal      972

In [47]:
#Calculating sum of all properties to use for percentage calculation
total_count_2 = sum(leg_illeg_df["count"])
#Creating variable to hold percentage data and calculating percentage 
prcnt_2 = (leg_illeg_df["count"])/total_count_2*100

In [48]:
#Adding "percentage" column to Data Ftame in % format
leg_illeg_df['percentage'] = prcnt_2.map('{:,.2f}%'.format)
leg_illeg_df

         count percentage
illegal
illegal   3850     79.84%
legal      972     20.16%

In [49]:
leg_illeg_df.to_csv("Output/legal.csv")

In [50]:
#Making a copy of a data set
nh= mapping_df.copy()
#Grouping values by "neighbourhood_cleansed" and "room_type" and counting properties by room type
nh = nh.groupby(["neighbourhood_cleansed","room_type"])["room_type"].count()
#Converting groupby results into Data Frame
nh_df = pd.DataFrame(nh)
#Renaming column "room_type" to "count"
nh_df = nh_df.rename(columns={ "room_type": "count"})
nh_df

                                        count
neighbourhood_cleansed room_type
Bayview                Entire home/apt     80
                       Private room       145
                       Shared room          2
Bernal Heights         Entire home/apt    266
                       Private room       135
...                                       ...
West of Twin Peaks     Entire home/apt     73
                       Private room        73
Western Addition       Entire home/apt    384
                       Private room       215
                       Shared room         26

[97 rows x 1 columns]

In [51]:
#Using pivot function to restructure Data Frame
table = pd.pivot_table(nh_df, values='count',
                    columns="room_type", index= "neighbourhood_cleansed")
#Changing NaN value to 0
table= table.fillna(0)
#Changing floats to int 
table["Entire home/apt"] = table["Entire home/apt"].astype(int)
table["Shared room"] = table["Shared room"].astype(int)
table["Private room"] = table["Private room"].astype(int)
#Renaming columns
table = table.rename(columns={ "Entire home/apt": "entire_house",
                               "Private room": "private_room",
                               "Shared room": "shared_room"
                             })
#sum_ent=(table["Entire home/apt"]).sum()
#sum_pr=(table["Private room"]).sum()
#sum_sh=(table["Shared room"]).sum()
#sum_ttl = sum_ent+sum_pr+sum_sh
#entire_house, private_room, shared_room
table

room_type               entire_house  private_room  shared_room
neighbourhood_cleansed
Bayview                           80           145            2
Bernal Heights                   266           135            1
Castro/Upper Market              297           147            2
Chinatown                        100            44            9
Crocker Amazon                    22            28            1
Diamond Heights                    8             8            0
Downtown/Civic Center            346           361           30
Excelsior                         79           100            1
Financial District               158            49           15
Glen Park                         50            12            0
Golden Gate Park                   4             2            0
Haight Ashbury                   226           129           53
Inner Richmond                   134            82           25
Inner Sunset                     112            51            4
Lakeshore                         25            37            1
Marina                           141            44            0
Mission                          454           276           23
Nob Hill                         192           143           18
Noe Valley                       216           101            1
North Beach                      120            68           37
Ocean View                        54            74            8
Outer Mission                     76            93            4
Outer Richmond                   104            66            2
Outer Sunset                     157           157            6
Pacific Heights                  129            44            0
Parkside                          79            59            6
Potrero Hill                     168            82            2
Presidio                           0             1            0
Presidio Heights                  21             3            0
Russian Hill                     155            47            7
Seacliff                          12             8            0
South of Market                  532           157           29
Treasure Island/YBI                1             0            0
Twin Peaks                        48            25            0
Visitacion Valley                 42            28            0
West of Twin Peaks                73            73            0
Western Addition                 384           215           26

In [52]:
table.to_csv("Output/grouped_neighborhoods.csv")